name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/packages
            ~/.platformio/platforms
            ~/.platformio/toolchains
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Release Binary
        run: pio run -e release

      - name: Build Debug Binary
        run: pio run -e debug
