name: Deploy
on:
  workflow_run:
    workflows: PlatformIO CI
    branches: main
    types: completed

jobs:
  deploy:
    name: Release and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: "true"

      - name: Create release
        run: gh release create "$TAG_NAME" --notes "$BODY"
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.changelog.outputs.tag }}
          BODY: ${{ steps.changelog.outputs.clean_changelog }}

